
// Code generated by stanc v2.28.1
#include <stan/model/model_header.hpp>
namespace cryo_bife_model_namespace {

using stan::io::dump;
using stan::model::assign;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 19> locations_array__ = 
{" (found before start of program)",
 " (in '/home/jgiraldob/path_optimization_github/cryoBIFE/cryoBIFE/stan/cryo-bife.stan', line 86, column 2 to column 18)",
 " (in '/home/jgiraldob/path_optimization_github/cryoBIFE/cryoBIFE/stan/cryo-bife.stan', line 87, column 2 to column 23)",
 " (in '/home/jgiraldob/path_optimization_github/cryoBIFE/cryoBIFE/stan/cryo-bife.stan', line 90, column 2 to column 46)",
 " (in '/home/jgiraldob/path_optimization_github/cryoBIFE/cryoBIFE/stan/cryo-bife.stan', line 93, column 2 to column 27)",
 " (in '/home/jgiraldob/path_optimization_github/cryoBIFE/cryoBIFE/stan/cryo-bife.stan', line 94, column 2 to column 18)",
 " (in '/home/jgiraldob/path_optimization_github/cryoBIFE/cryoBIFE/stan/cryo-bife.stan', line 95, column 2 to column 20)",
 " (in '/home/jgiraldob/path_optimization_github/cryoBIFE/cryoBIFE/stan/cryo-bife.stan', line 81, column 2 to column 17)",
 " (in '/home/jgiraldob/path_optimization_github/cryoBIFE/cryoBIFE/stan/cryo-bife.stan', line 82, column 2 to column 17)",
 " (in '/home/jgiraldob/path_optimization_github/cryoBIFE/cryoBIFE/stan/cryo-bife.stan', line 83, column 27 to column 28)",
 " (in '/home/jgiraldob/path_optimization_github/cryoBIFE/cryoBIFE/stan/cryo-bife.stan', line 83, column 30 to column 31)",
 " (in '/home/jgiraldob/path_optimization_github/cryoBIFE/cryoBIFE/stan/cryo-bife.stan', line 83, column 2 to column 38)",
 " (in '/home/jgiraldob/path_optimization_github/cryoBIFE/cryoBIFE/stan/cryo-bife.stan', line 86, column 9 to column 14)",
 " (in '/home/jgiraldob/path_optimization_github/cryoBIFE/cryoBIFE/stan/cryo-bife.stan', line 90, column 10 to column 11)",
 " (in '/home/jgiraldob/path_optimization_github/cryoBIFE/cryoBIFE/stan/cryo-bife.stan', line 68, column 4 to column 24)",
 " (in '/home/jgiraldob/path_optimization_github/cryoBIFE/cryoBIFE/stan/cryo-bife.stan', line 69, column 4 to column 60)",
 " (in '/home/jgiraldob/path_optimization_github/cryoBIFE/cryoBIFE/stan/cryo-bife.stan', line 67, column 40 to line 70, column 3)",
 " (in '/home/jgiraldob/path_optimization_github/cryoBIFE/cryoBIFE/stan/cryo-bife.stan', line 77, column 4 to column 32)",
 " (in '/home/jgiraldob/path_optimization_github/cryoBIFE/cryoBIFE/stan/cryo-bife.stan', line 76, column 43 to line 78, column 3)"};


template <bool propto__, typename T0__, typename T1__>
stan::promote_args_t<stan::value_type_t<T0__>,
T1__>
rw1_lpdf(const T0__& alpha_arg__, const T1__& tau, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::value_type_t<T0__>,
          T1__>;
  int current_statement__ = 0; 
  const auto& alpha = to_ref(alpha_arg__);
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  (void) DUMMY_VAR__;  // suppress unused var warning
  try {
    int N;
    N = std::numeric_limits<int>::min();
    
    current_statement__ = 14;
    N = rows(alpha);
    current_statement__ = 15;
    return normal_lpdf<false>(rvalue(alpha, "alpha", index_min_max(2, N)),
             rvalue(alpha, "alpha", index_min_max(1, (N - 1))),
             pow(tau, -0.5));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
  
}

struct rw1_lpdf_functor__ {
template <bool propto__, typename T0__, typename T1__>
stan::promote_args_t<stan::value_type_t<T0__>,
T1__>
operator()(const T0__& alpha, const T1__& tau, std::ostream* pstream__)  const 
{
return rw1_lpdf<propto__>(alpha, tau, pstream__);
}
};

template <bool propto__, typename T0__, typename T1__>
stan::promote_args_t<stan::value_type_t<T0__>,
stan::value_type_t<T1__>>
image_lpdf(const T0__& Pmat_arg__, const T1__& rho_arg__,
           std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::value_type_t<T0__>,
          stan::value_type_t<T1__>>;
  int current_statement__ = 0; 
  const auto& Pmat = to_ref(Pmat_arg__);
  const auto& rho = to_ref(rho_arg__);
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  (void) DUMMY_VAR__;  // suppress unused var warning
  try {
    current_statement__ = 17;
    return sum(stan::math::log(multiply(Pmat, rho)));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
  
}

struct image_lpdf_functor__ {
template <bool propto__, typename T0__, typename T1__>
stan::promote_args_t<stan::value_type_t<T0__>,
stan::value_type_t<T1__>>
operator()(const T0__& Pmat, const T1__& rho, std::ostream* pstream__)  const 
{
return image_lpdf<propto__>(Pmat, rho, pstream__);
}
};

class cryo_bife_model final : public model_base_crtp<cryo_bife_model> {

 private:
  int M;
  int N;
  Eigen::Matrix<double, -1, -1> Pmat__;
  int G_1dim__; 
  Eigen::Map<Eigen::Matrix<double, -1, -1>> Pmat{nullptr, 0, 0};
 
 public:
  ~cryo_bife_model() { }
  
  inline std::string model_name() const final { return "cryo_bife_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.28.1", "stancflags = "};
  }
  
  
  cryo_bife_model(stan::io::var_context& context__,
                  unsigned int random_seed__ = 0,
                  std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "cryo_bife_model_namespace::cryo_bife_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 7;
      context__.validate_dims("data initialization","M","int",
           std::vector<size_t>{});
      M = std::numeric_limits<int>::min();
      
      current_statement__ = 7;
      M = context__.vals_i("M")[(1 - 1)];
      current_statement__ = 7;
      check_greater_or_equal(function__, "M", M, 0);
      current_statement__ = 8;
      context__.validate_dims("data initialization","N","int",
           std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      
      current_statement__ = 8;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 8;
      check_greater_or_equal(function__, "N", N, 0);
      current_statement__ = 9;
      validate_non_negative_index("Pmat", "N", N);
      current_statement__ = 10;
      validate_non_negative_index("Pmat", "M", M);
      current_statement__ = 11;
      context__.validate_dims("data initialization","Pmat","double",
           std::vector<size_t>{static_cast<size_t>(N),
            static_cast<size_t>(M)});
      Pmat__ = Eigen::Matrix<double, -1, -1>(N, M);
      new (&Pmat) Eigen::Map<Eigen::Matrix<double, -1, -1>>(Pmat__.data(), N, M);
      
      
      {
        std::vector<local_scalar_t__> Pmat_flat__;
        current_statement__ = 11;
        Pmat_flat__ = context__.vals_r("Pmat");
        current_statement__ = 11;
        pos__ = 1;
        current_statement__ = 11;
        for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
          current_statement__ = 11;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 11;
            assign(Pmat, Pmat_flat__[(pos__ - 1)],
              "assigning variable Pmat", index_uni(sym2__), index_uni(sym1__));
            current_statement__ = 11;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 11;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 11;
        for (int sym2__ = 1; sym2__ <= M; ++sym2__) {
          current_statement__ = 11;
          check_greater_or_equal(function__, "Pmat[sym1__, sym2__]",
                                 rvalue(Pmat, "Pmat",
                                   index_uni(sym1__), index_uni(sym2__)), 0);
        }
      }
      current_statement__ = 11;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 11;
        for (int sym2__ = 1; sym2__ <= M; ++sym2__) {
          current_statement__ = 11;
          check_less_or_equal(function__, "Pmat[sym1__, sym2__]",
                              rvalue(Pmat, "Pmat",
                                index_uni(sym1__), index_uni(sym2__)), 1);
        }
      }
      current_statement__ = 12;
      G_1dim__ = std::numeric_limits<int>::min();
      
      current_statement__ = 12;
      G_1dim__ = (M - 1);
      current_statement__ = 12;
      validate_non_negative_index("G", "M - 1", G_1dim__);
      current_statement__ = 13;
      validate_non_negative_index("rho", "M", M);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = G_1dim__ + 1;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "cryo_bife_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<local_scalar_t__, -1, 1> G;
      G = Eigen::Matrix<local_scalar_t__, -1, 1>(G_1dim__);
      stan::math::fill(G, DUMMY_VAR__);
      
      current_statement__ = 1;
      G = in__.template read<Eigen::Matrix<local_scalar_t__, -1, 1>>(
            G_1dim__);
      local_scalar_t__ lambda;
      lambda = DUMMY_VAR__;
      
      current_statement__ = 2;
      lambda = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                 0, lp__);
      Eigen::Matrix<local_scalar_t__, -1, 1> rho;
      rho = Eigen::Matrix<local_scalar_t__, -1, 1>(M);
      stan::math::fill(rho, DUMMY_VAR__);
      
      current_statement__ = 3;
      assign(rho, softmax(minus(append_row(G, 0))), "assigning variable rho");
      current_statement__ = 3;
      check_simplex(function__, "rho", rho);
      {
        current_statement__ = 4;
        lp_accum__.add(lognormal_lpdf<propto__>(lambda, 0, 3));
        current_statement__ = 5;
        lp_accum__.add(rw1_lpdf<propto__>(G, lambda, pstream__));
        current_statement__ = 6;
        lp_accum__.add(image_lpdf<propto__>(Pmat, rho, pstream__));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "cryo_bife_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<double, -1, 1> G;
      G = Eigen::Matrix<double, -1, 1>(G_1dim__);
      stan::math::fill(G, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 1;
      G = in__.template read<Eigen::Matrix<local_scalar_t__, -1, 1>>(
            G_1dim__);
      double lambda;
      lambda = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      lambda = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                 0, lp__);
      Eigen::Matrix<double, -1, 1> rho;
      rho = Eigen::Matrix<double, -1, 1>(M);
      stan::math::fill(rho, std::numeric_limits<double>::quiet_NaN());
      
      out__.write(G);
      out__.write(lambda);
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 3;
      assign(rho, softmax(minus(append_row(G, 0))), "assigning variable rho");
      current_statement__ = 3;
      check_simplex(function__, "rho", rho);
      if (emit_transformed_parameters__) {
        out__.write(rho);
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_std_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__, -1, 1> G;
      G = Eigen::Matrix<local_scalar_t__, -1, 1>(G_1dim__);
      stan::math::fill(G, DUMMY_VAR__);
      
      for (int sym1__ = 1; sym1__ <= G_1dim__; ++sym1__) {
        assign(G, in__.read<local_scalar_t__>(),
          "assigning variable G", index_uni(sym1__));
      }
      out__.write(G);
      local_scalar_t__ lambda;
      lambda = DUMMY_VAR__;
      
      lambda = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, lambda);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"G", "lambda", "rho"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{
                                                                   static_cast<size_t>(G_1dim__)
                                                                   },
      std::vector<size_t>{}, std::vector<size_t>{static_cast<size_t>(M)}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= G_1dim__; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "G" + '.' + std::to_string(sym1__));
      } 
    }
    param_names__.emplace_back(std::string() + "lambda");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "rho" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= G_1dim__; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "G" + '.' + std::to_string(sym1__));
      } 
    }
    param_names__.emplace_back(std::string() + "lambda");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= (M - 1); ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "rho" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"G\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(G_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"lambda\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"rho\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(M) + "},\"block\":\"transformed_parameters\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"G\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(G_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"lambda\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"rho\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string((M - 1)) + "},\"block\":\"transformed_parameters\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  (G_1dim__ + 1);
      const size_t num_transformed = M;
      const size_t num_gen_quantities = 0;
      std::vector<double> vars_vec(num_params__
       + (emit_transformed_parameters * num_transformed)
       + (emit_generated_quantities * num_gen_quantities));
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        vars_vec.data(), vars_vec.size());
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  (G_1dim__ + 1);
      const size_t num_transformed = M;
      const size_t num_gen_quantities = 0;
      vars.resize(num_params__
        + (emit_transformed_parameters * num_transformed)
        + (emit_generated_quantities * num_gen_quantities));
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 2> names__{"G", "lambda"};
      const std::array<Eigen::Index, 2> constrain_param_sizes__{G_1dim__, 1};
      const auto num_constrained_params__ = std::accumulate(
        constrain_param_sizes__.begin(), constrain_param_sizes__.end(), 0);
    
     std::vector<double> params_r_flat__(num_constrained_params__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < constrain_param_sizes__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(num_params_r__);
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
    
};
}
using stan_model = cryo_bife_model_namespace::cryo_bife_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return cryo_bife_model_namespace::profiles__;
}

#endif


